### ISSUE TITLE
Treating ignored record fields

### ISSUE THREAD

**Issue by Lupus** [janestreet/ppx_js_style#2]
More of a question on Jane Street style itself than on the checker though :)

What do you do with ignored record fields in patterns, like say I'm pattern matching a record with 10 fields, capture only 2 of those, and ignore the rest. Should all of them be spelled out with types following the same logic for ignored function return values?

Sorry if I'm asking this question in a wrong place.

**Comment by ceastlund** [comment]
We don't generally annotate types in this situation, because the field name serves that purpose. We usually just write each one like `; field3 = _`. I'd also only pattern match on the whole record if I thought the code would need to be updated in the future with the addition of more fields. In most cases where I just needed 2 out of 10 fields, I'd just bind the record to a name and use field accessors like `x.field1` to get at what I need.

**Comment by Lupus** [comment]
Thanks @ceastlund ! Does it make sense to include this into Jane Street style guide for the sake of completeness maybe?

**Comment by ceastlund** [comment]
Sounds sensible, thanks. I'll bring that up internally.
